dist: trusty
sudo: required
language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ruby

script:
  - ls ~/build/uthash/src
  - make travis BRANCH=$TRAVIS_BRANCH


notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
