dist: trusty
sudo: required
language: c

addons:
  sonarqube:
    branches:
      - master
      - dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libbsd-dev

script:
  - sonar-scanner -X -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarqube.com
  - make travis BRANCH=$TRAVIS_BRANCH


notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
