dist: trusty
sudo: required
language: c

addons:
  sonarqube:
    branches:
      - master
      - dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libbsd-dev

script:
  - sonar-scanner -X -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarqube.com
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - make travis BRANCH=$BRANCH


notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
