dist: trusty
sudo: required
language: c

addons:
  sonarqube:
    branches:
      - master
      - dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install build-essential
  - sudo apt-get install -y yum
  - curl -s https://packagecloud.io/install/repositories/camflow/provenance/script.rpm.sh | sudo bash
  - sudo yum install kernel-headers-4.11.3camflow_0.3.2-2.x86_64

script:
  - sonar-scanner -X -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarqube.com
  - make prepare
  - make all

notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
