dist: trusty
sudo: required
language: c

addons:
  sonarqube:
    branches:
      - master
      - dev

before_install:
  - sudo apt-get update -qq

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - sonar-scanner -X -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarqube.com
  - git clone https://github.com/CamFlow/camflow-dev.git
  - cd camflow-dev
  - git checkout $BRANCH
  - cd ..
  - make prepare
  - sed -i -e 's/#include <linux/provenance.h>/#include "../camflow-dev/include/uapi/linux/provenance.h"/g' ./include/provenance.h
  - sed -i -e 's/#include <linux/provenance.h>/#include "../camflow-dev/include/uapi/linux/provenance.h"/g' ./include/provenancefitler.h
  - sed -i -e 's/#include <linux/provenance.h>/#include "../camflow-dev/include/uapi/linux/provenance.h"/g' ./include/provenanceutils.h
  - sed -i -e 's/#include <linux/camflow.h>/#include "../camflow-dev/include/uapi/linux/camflow.h"/g' ./src/provenanceProvJSON.c
  - make all
  - make install

notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
