dist: trusty
sudo: required
language: c

addons:
  sonarqube:
    branches:
      - master
      - dev

before_install:
  - sudo apt-get update -qq

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - sonar-scanner -X -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarqube.com
  - git clone https://github.com/CamFlow/camflow-dev.git
  - cd camflow-dev
  - git checkout $BRANCH
  - cd ..
  - make prepare
  - sed -i -e 's/INCLUDES = -I..\/threadpool -I..\/include -I..\/uthash\/uthash\/src/INCLUDES = -I..\/threadpool -I..\/include -I..\/uthash\/uthash\/src -I.\/camflow-dev\/include\/uapi/g' .//src/Makefile
  - cat ./src/Makefile
  - make all
  - make install

notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
